spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URI}
          clone-on-start: true
          username: Ganza-Kevin-Murinda
          password: ${GITHUB-TOKEN}
server:
  port: 8888

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

# Actuator for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,configprops
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.web: DEBUG

